# Generated by Django 5.0.7 on 2024-07-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='preco',
            new_name='sobrenome',
        ),
    ]
